#!/usr/bin/env python3
"""
Собирает IPv4/IPv6-префиксы популярных сервисов для proxy/VPN split-tunnel.

Источники двух типов:
  1. Официальные фиды провайдера (самые точные, где есть).
  2. Announced prefixes по ASN через публичный RIPEstat API (без ключа).

Часть сервисов (см. SHARED_INFRA_NOTES) сидит на общих CDN/облаках —
для них точный список по IP принципиально неполный или пересекается
с чужими доменами на той же инфраструктуре. Такие сервисы либо не
включены, либо помечены в README отдельно.
"""
from __future__ import annotations

import ipaddress
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

USER_AGENT = "network-prefixes-fetcher/1.0 (+https://github.com/evgen66rus/network-prefixes)"


def http_get(url: str, timeout: int = 30) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def ripestat_prefixes(asn: int) -> list[str]:
    url = f"https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS{asn}"
    data = json.loads(http_get(url))
    return [p["prefix"] for p in data["data"]["prefixes"]]


def dedupe_and_sort(prefixes: list[str]) -> list[str]:
    nets = set()
    for p in prefixes:
        try:
            nets.add(ipaddress.ip_network(p, strict=False))
        except ValueError:
            continue
    return [str(n) for n in sorted(nets, key=lambda n: (n.version, n))]


# --- Официальные фиды -------------------------------------------------

def fetch_telegram() -> list[str]:
    text = http_get("https://core.telegram.org/resources/cidr.txt").decode()
    return [line.strip() for line in text.splitlines() if line.strip()]


def fetch_cloudflare() -> list[str]:
    v4 = http_get("https://www.cloudflare.com/ips-v4/").decode().splitlines()
    v6 = http_get("https://www.cloudflare.com/ips-v6/").decode().splitlines()
    return [l.strip() for l in v4 + v6 if l.strip()]


def fetch_amazon() -> list[str]:
    data = json.loads(http_get("https://ip-ranges.amazonaws.com/ip-ranges.json"))
    v4 = [p["ip_prefix"] for p in data["prefixes"]]
    v6 = [p["ipv6_prefix"] for p in data["ipv6_prefixes"]]
    return v4 + v6


def fetch_microsoft() -> list[str]:
    # Официальная страница отдаёт редирект на changeable download id — вытаскиваем
    # текущий URL json-файла Service Tags (Public cloud) со страницы подтверждения.
    page = http_get(
        "https://www.microsoft.com/en-us/download/details.aspx?id=56519"
    ).decode(errors="ignore")
    m = re.search(r'https://download\.microsoft\.com/download/[^"\']+ServiceTags_Public[^"\']+\.json', page)
    if not m:
        raise RuntimeError("microsoft: не удалось найти ссылку на ServiceTags_Public JSON")
    data = json.loads(http_get(m.group(0)))
    prefixes = []
    for value in data["values"]:
        prefixes.extend(value["properties"].get("addressPrefixes", []))
    return prefixes


# --- ASN-based ---------------------------------------------------------

ASN_SERVICES: dict[str, list[int]] = {
    "meta": [32934, 63293, 54115],           # Facebook, Facebook-Offnet, Facebook-Corp
    "twitter": [13414],                       # Twitter/X
    "netflix": [2906, 40027, 55095],          # Netflix Inc + Open Connect
    "youtube_google": [15169, 19527, 36040],  # Google, Google-2, YouTube (без AS396982=GCP, это чужой шаринг!)
    "linkedin": [14413],
    "tiktok": [138699],
    "railway": [400940],
    "openai": [401518],                       # у OpenAI своих префиксов почти нет, см. README
}

# Официальные фиды: имя_файла -> функция
OFFICIAL_SERVICES = {
    "telegram": fetch_telegram,
    "cloudflare": fetch_cloudflare,
    "amazon": fetch_amazon,
    "microsoft": fetch_microsoft,
}

# Сервисы без надёжного списка по IP (общий CDN/хостинг у третьих лиц) —
# файлы не генерируются, только заметка в README.
SHARED_INFRA_NOTES = {
    "discord": "Голос/CDN идут через Cloudflare и i3D.net (AS49544) — тот же ASN хостит множество других клиентов i3D, точный список по IP невозможен без ложных срабатываний.",
    "pornhub": "Aylo/Pornhub отдаётся через стороннего хостера (Reflected Networks), выделенного ASN нет.",
    "openai_web": "chatgpt.com/chat-фронтенд идёт через Cloudflare (общий anycast) — своя выделенная сеть (AS401518) покрывает лишь малую часть инфраструктуры.",
}


def write_service_file(name: str, prefixes: list[str], source_note: str) -> None:
    out = DATA_DIR / f"{name}.txt"
    lines = dedupe_and_sort(prefixes)
    out.write_text(f"# source: {source_note}\n# generated by scripts/fetch.py — do not edit by hand\n" + "\n".join(lines) + "\n")
    print(f"{name}: {len(lines)} prefixes -> {out.relative_to(ROOT)}")


def main() -> int:
    DATA_DIR.mkdir(exist_ok=True)
    had_errors = False

    for name, fn in OFFICIAL_SERVICES.items():
        try:
            write_service_file(name, fn(), "official feed")
        except Exception as e:  # noqa: BLE001
            print(f"[ERROR] {name}: {e}", file=sys.stderr)
            had_errors = True

    for name, asns in ASN_SERVICES.items():
        try:
            prefixes: list[str] = []
            for asn in asns:
                prefixes.extend(ripestat_prefixes(asn))
            asn_list = ", ".join(f"AS{a}" for a in asns)
            write_service_file(name, prefixes, f"RIPEstat announced-prefixes for {asn_list}")
        except Exception as e:  # noqa: BLE001
            print(f"[ERROR] {name}: {e}", file=sys.stderr)
            had_errors = True

    # combined file
    all_prefixes: list[str] = []
    for f in sorted(DATA_DIR.glob("*.txt")):
        if f.name == "all.txt":
            continue
        for line in f.read_text().splitlines():
            if line and not line.startswith("#"):
                all_prefixes.append(line)
    write_service_file("all", all_prefixes, "combined from all data/*.txt")

    return 1 if had_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
